api/urls.py
#URL routing settings for api objects that loads the correct veiws to send to the front end 
from django.conf.urls import url
from . import views


app_name = "api"
urlpatterns = [	
	url(r'^cart', views.CartView.as_view(), name="cart"),
	url(r'^payment', views.payment, name="payment"),
	]

hedera_django_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("api.urls", namespace="api")),
    path('', include("users.urls", namespace="users"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
#URL routing settings for user objects that loads the correct veiws to send to the front end 
from django.conf.urls import url
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
	
	path('', views.sign_in, name="sign-in"),
	url(r'^sign-up', views.sign_up, name="sign-up"),
	url(r'^sign-out', views.sign_out, name="sign-out"),
	url(r'^account', views.AccountView.as_view(), name="account"),
	]

api/models.py
#these are the models used by the api module 
#They repersent 'api' object constructors 
from django.db import models
from django.contrib.auth.models import User

class Invoicing(models.Model):

	class Meta:
		verbose_name_plural = "Invoicing"
		ordering = ["-timestamp"]

	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	tran_id = models.CharField(max_length=100)
	description = models.CharField(max_length=100)
	amount = models.IntegerField(verbose_name="Amount - tinybar (tℏ)")

	@property
	def AmountConversion(self):
		return self.amount / 100_000

	def __str__(self):
		return f'{self.user}'

api/views.py
#these are the views  used by the api module 
#They repersent the code that interfaces with the front end 
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import JsonResponse

from .mixins import (
	HederaAccount,
	HederaPayment,
	HederaData,
	)

from .models import (
	Invoicing
	)



@method_decorator(login_required, name='dispatch')
class CartView(TemplateView):
	'''
	Basic template view to render a demo cart
	'''
	template_name = "api/cart.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		#we need to get the user's hbar balance
		user = self.request.user
		hedera_data = HederaData(user = user)
		context["balance"] = hedera_data.balance()
		
		return context




@login_required
def payment(request):

	'''
	AJAX function to handle a Hedera payment
	'''

	if request.method == "POST":

		user = request.user
		description = request.POST.get("description", None)
		amount = request.POST.get('amount')

		payment = HederaPayment(
			user=user,
			amount=amount,
			description = description,
			).create()

		if payment["message"] == "Perfect":

			invoice = Invoicing(
				user = user,
				amount = int(amount) * 100_000,
				tran_id = payment["tran_id"],
				description = description,
				)
			invoice.save()

			data = {'result': 'Success', "message":payment["message"]}
			return JsonResponse(data)

		else:

			data = {'result': 'Error', "message":payment["message"]}
			return JsonResponse(data)

	else:

		data = {'result': 'Error'}
		return JsonResponse(data)

api/templates/api/cart.html
{% extends 'users/base.html' %}
{% load static %}

{% block extend_head %}



{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
    <li><a href="{% url 'users:account' %}">Demo User Account</a></li>
    <li><a class="active" href="{% url 'api:cart' %}">Demo Cart</a></li>
    <li><a href="{% url 'users:sign-out' %}">Sign out</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Hedera Hashgraph API Demo - Cart</h3>

<div class="container">

    <h3>This is the balance of your demo Hedera Hashgraph wallet</h3>
    <table id="saved-cards">
        <thead>
            <tr>
                <th>Field</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Balance</td>
                <td>{{balance}}</td>
            </tr>

        </tbody>
    </table>


    <h3>Official HBAR cryptocurrency denominations</h3>
    <table id="saved-cards">
        <thead>
            <tr>
                <th>Denomination</th>
                <th>Hbars</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>gigabar 1 Gℏ</td>
                <td>1,000,000,000 ℏ</td>
            </tr>
            <tr>
                <td>megabar 1 Mℏ</td>
                <td>1,000,000 ℏ</td>
            </tr>
            <tr>
                <td>kilobar 1 kℏ</td>
                <td>1,000 ℏ</td>
            </tr>
            <tr>
                <td>hbar 1 ℏ</td>
                <td>1 ℏ</td>
            </tr>
            <tr>
                <td>millibar 1,000 mℏ</td>
                <td>1 ℏ</td>
            </tr>
            <tr>
                <td>microbar 1,000,000 μℏ</td>
                <td>1 ℏ</td>
            </tr>
            <tr>
                <td>tinybar 100,000,000 tℏ</td>
                <td>1 ℏ</td>
            </tr>

        </tbody>
    </table>

    <div>
        <br>
        <button type="submit" class="use-hbar" onclick="payWithHbar('Shirt', '6000')">Pay 6000 millibar for a shirt</button>
    </div>
    <div>
        <br>
        <button type="submit" class="use-hbar" onclick="payWithHbar('Pants', '4500')">Pay 4500 millibar for pants</button>
    </div>
    <div>
        <br>
        <button type="submit" class="use-hbar" onclick="payWithHbar('Shoes', '8700')">Pay 8700 millibar for shoes</button>
    </div>






</div>


{% endblock %}

{% block extend_footer %}

{% endblock extend_footer %}