api/urls.py
#URL routing settings for api objects that loads the correct veiws to send to the front end 
from django.conf.urls import url
from . import views


app_name = "api"
urlpatterns = [	
	url(r'^cart', views.CartView.as_view(), name="cart"),
	url(r'^payment', views.payment, name="payment"),
	]

hedera_django_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("api.urls", namespace="api")),
    path('', include("users.urls", namespace="users"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
#URL routing settings for user objects that loads the correct veiws to send to the front end 
from django.conf.urls import url
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
	
	path('', views.sign_in, name="sign-in"),
	url(r'^sign-up', views.sign_up, name="sign-up"),
	url(r'^sign-out', views.sign_out, name="sign-out"),
	url(r'^account', views.AccountView.as_view(), name="account"),
	]

users/models.py
#these are the models used by the user module 
#They repersent 'user' object constructors 
from django.db import models
from django.contrib.auth.models import User



class UserProfile(models.Model):

	'''
	Our UserProfile model extends the built-in Django User Model
	'''

	class Meta:
		verbose_name_plural = "User profiles"
		ordering = ["-timestamp"]
	
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	telephone = models.CharField(max_length=15, null=True, blank=True)
	address = models.CharField(verbose_name="Address",max_length=100, null=True, blank=True)
	town = models.CharField(verbose_name="Town/City",max_length=100, null=True, blank=True)
	state = models.CharField(verbose_name="State",max_length=100, null=True, blank=True)
	post_code = models.CharField(verbose_name="Post Code",max_length=8, null=True, blank=True)
	country = models.CharField(verbose_name="Country",max_length=100, null=True, blank=True, default="UK")
	is_active = models.BooleanField(default = True)

	acc = models.CharField(max_length=20, null=True, blank=True)
	pubkey = models.CharField(max_length=200, null=True, blank=True)
	privatekey = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return f'{self.user}'

users/forms.py
#these are the forms used by the user module 
#They fill the feilds required by the user models to create user objects 
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile


class UserForm(UserCreationForm):
	'''
	Form that uses built-in UserCreationForm to handel user creation
	'''
	first_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your first name..'}))
	last_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your last name..'}))
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Confirm Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )




class UserProfileForm(forms.ModelForm):
	'''
	Basic model-form for our user profile that extends Django user model.
	'''
	
	telephone = forms.CharField(max_length=15, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Telephone..'}))
	address = forms.CharField(max_length=100, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*First line of address..'}))
	town = forms.CharField(max_length=100, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*Town or City..'}))
	state = forms.CharField(max_length=100, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*State..'}))
	
	post_code = forms.CharField(max_length=8, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*Postal Code..'}))


	class Meta:
		model = UserProfile
		fields = ('telephone', 'address', 'town', 'state', 'post_code', )





class AuthForm(AuthenticationForm):
	'''
	Form that uses built-in AuthenticationForm to handel user auth
	'''
	
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('username','password', )

users/views.py
#these are the views  used by the user module 
#They repersent the code that interfaces with the front end 
   
from django.shortcuts import render, redirect, reverse
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, JsonResponse
from django.conf import settings


from .mixins import (
	FormErrors,
	)

from .forms import (
	UserForm,
	UserProfileForm,
	AuthForm,
	)

from api.mixins import (
	HederaAccount,
	HederaData
	)

from api.models import Invoicing


result = "Error"
message = "Something went wrong. Please check and try again"

def sign_up(request):
	'''
	Basic view for user sign up
	'''
	
	#redirect if user is already signed in
	if request.user.is_authenticated:
		return redirect(reverse('users:account'))

	u_form = UserForm()
	up_form = UserProfileForm()
	
	if request.is_ajax():
		u_form = UserForm(data = request.POST)
		up_form = UserProfileForm(data = request.POST)
		
		#if both forms are valid, do something
		if u_form.is_valid() and up_form.is_valid():
			user = u_form.save()

			#commit = False is used as userprofile.user can not be null
			up = up_form.save(commit = False)
			up.user = user
			up.save()
			user.is_active = True
			user.email = user.username
			user.save()

			#create a Hedera account for user
			hed = HederaAccount(user)
			
			login(request, user)
			result = "Success"
			message = "Your profile is now active"
		else:
			message = FormErrors(u_form, up_form)

		data = {'result': result, 'message': message}
		return JsonResponse(data)
		
	context = {'u_form':u_form, 'up_form':up_form}
	return render(request, 'users/sign_up.html', context)




def sign_in(request):
	'''
	Basic view for user sign in
	'''

	#redirect if user is already signed in
	if request.user.is_authenticated:
		return redirect(reverse('users:account'))
	
	a_form = AuthForm()

	if request.is_ajax():
		a_form = AuthForm(data = request.POST)
		if a_form.is_valid():
			username = a_form.cleaned_data.get('username')
			password = a_form.cleaned_data.get('password')

			#authenticate Django built in authenticate - https://docs.djangoproject.com/en/3.1/ref/contrib/auth/
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				message = 'You are now logged in'
				result = "Success"

		else:
			message = FormErrors(a_form)
		
		data = {'result': result, 'message': message}
		return JsonResponse(data)
	
	context = {'a_form':a_form}
	return render(request, 'users/sign_in.html', context)




def sign_out(request):
	'''
	Basic view for user sign out
	'''
	logout(request)
	return redirect(reverse('users:sign-in'))




@method_decorator(login_required, name='dispatch')
class AccountView(TemplateView):
	'''
	Basic template view to render a demo user account
	'''
	template_name = "users/account.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		#we need to get the user's hbar balance
		user = self.request.user
		hedera_data = HederaData(user = user)
		context["balance"] = hedera_data.balance()

		#get transactions
		transactions = Invoicing.objects.filter(user = user)
		context["transactions"] = transactions

		return context

users/templates/users/account.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="{% url 'users:account' %}">Demo User Account</a></li>
  <li><a href="{% url 'api:cart' %}">Demo Cart</a></li>
  <li><a href="{% url 'users:sign-out' %}">Sign out</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Hedera Hashgraph API Demo - User Account</h3>

<div class="container">

  <h4>User account details</h4>
  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Username</td>
        <td>{{request.user.username}}</td>      
      </tr>
      <tr>
        <td>Name</td>
        <td>{{request.user.first_name}} {{request.user.last_name}}</td>      
      </tr>
      <tr>
        <td>Telephone</td>
        <td>{{request.user.userprofile.telephone}}</td>      
      </tr>
      <tr>
        <td>Address</td>
        <td>
          <address>
            {{request.user.userprofile.address}}<br>
            {{request.user.userprofile.town}}<br>
            {{request.user.userprofile.state}}<br>
            {{request.user.userprofile.post_code}}<br>
          </address>
        </td>      
      </tr>

      <tr>
        <td>Balance</td>
        <td>{{balance}}</td>      
      </tr>

    </tbody>
  </table>



  {% if transactions %}
  <h4>Invoices</h4>
  <table>
    <thead>
      <tr>
          <th hidden>ID</th>
          <th>ID</th>
          <th>Date</th>
          <th>Description</th>
          <th>Amount</th>

      </tr>
      
    </thead>
    <tbody>
      {% for tran in transactions %}
      <tr>
        <td hidden>{{tran.id}}</td>
        <td>{{tran.tran_id}}</td>
        <td>{{tran.timestamp.date}}</td>
        <td>{{tran.description}}</td>
        <td>{{tran.amount}} tinybar</td>

      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

</div>

{% endblock %}


{% block extend_footer %}

{% endblock %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main.css' %}"></link>

    <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
    {% block extend_head %}

    {% endblock %}

</head>
<body>

    <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
    {% block extend_nav %}

    {% endblock %}

    <div class="div-container">

        {% include 'users/partials/logo.html' %}

        {% block content %}

        {% endblock %}

    </div>

    <!--visit https://code.jquery.com/ for jquery script-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
    {% block extend_footer %}

    {% endblock %}

    <script src="{% static 'main.js' %}"></script>


</body>
</html>

users/templates/users/sign_in.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
  <li><a href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Hedera Hashgraph API Demo - Sign In</h3>

<div class="container">

  <form id="signinform" method="POST" action="/">
    {% csrf_token %}
    <label for="username">Username</label>
    {{a_form.username}}

    <label for="password">Password</label>
    {{a_form.password}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Sign in</button>
 </form>

 {{a_form.errors}}

</div>


{% endblock %}


{% block extend_footer %}

{% endblock %}

users/templates/users/sign_up.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %}

<ul class="sidenav">
    <li><a href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
    <li><a class="active" href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Hedera Hashgraph API Demo - Sign Up</h3>

<div class="container">


    <form id="signupform" method="POST" action="/sign-up">
        {% csrf_token %}

        <label for="username">Username</label>
        {{u_form.username}}

        <label for="password1">Password</label>
        {{u_form.password1}}

        <label for="password2">Confirm Password</label>
        {{u_form.password2}}

        <label class="check-container">
            Show Passwords
            <input type="checkbox" onclick="showPword()">
            <span class="checkmark"></span>
        </label>

        <label for="first_name">First Name</label>
        {{u_form.first_name}}

        <label for="last_name">Last Name</label>
        {{u_form.last_name}}

        <label for="address">Address</label>
        {{up_form.address}}

        <label for="town">Town/City</label>
        {{up_form.town}}

        <label for="state">State</label>
        {{up_form.state}}

        <label for="post_code">Postal Code</label>
        {{up_form.post_code}}

        <label for="telephone">Telephone</label>
        {{up_form.telephone}}

        <button type="submit">Sign up</button>
    </form>

    {{u_form.errors}}
    {{up_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}